[package]
name = "cargo-jet"
description = "Build and run your Rust projects effortlessly on a remote machine! 🦀⚡"
repository = "https://github.com/luigiistcrazy/cargo-jet"
license = "GPL-3.0-or-later"
keywords = ["CLI-tool", "cargo", "remote", "compiling"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
version = "0.1.0"
edition = "2024"
authors = ["Luis Weitl <weitlluis@proton.me>"]

[dependencies]
anyhow = "1.0.98"
cargo_toml = "0.22.3"
clap = { version = "4.5.32", features = ["derive", "cargo"] }
colored = "3.0.0"
crossterm = "0.29.0"
serde = "1.0.219"
toml_edit = { version = "0.23.6", features = ["serde"] }

[profile.release]
opt-level = "s"
debug = "none"
strip = true
lto = "fat"
codegen-units = 1
